global:
  scrape_interval: 15s

scrape_configs:

# node exporter (https://github.com/prometheus/node_exporter)
- job_name: 'node'
  static_configs:
  - targets: ['monitoring_node-exporter:9100'] # change 192.168.100.x to your nodes IPs

# docker daemon (https://docs.docker.com/config/daemon/prometheus/)
- job_name: 'docker'
  static_configs:
  - targets: ['192.168.100.2:9323', '192.168.100.4:9323', '192.168.100.6:9323'] # change 192.168.100.x to your nodes IPs

# pushgateway
- job_name: 'pushgateway'
  honor_labels: true
  static_configs:
  - targets: ['monitoring_pushgateway:9091']
  basic_auth:
    username: 'admin' # change
    password: 'admin' # change # or use password_file instead (docker secrets)
    # password_file: '/run/secrets/node_exporter_password'


# postgres exporter (https://github.com/prometheus-community/postgres_exporter)
- job_name: 'postgres'
  static_configs:
  - targets: ['db_postgres-exporter:9187']
